<?php
return [
  [
    'title' => '品牌管理',
    'icon' => 'aicon ai-shezhi',
    'module' => 'brand',
    'url' => 'brand',
    'param' => '',
    'target' => '_self',
    'debug' => 0,
    'system' => 0,
    'nav' => 1,
    'sort' => 100,
    'childs' => [
      [
        'title' => '品牌管理',
        'icon' => '',
        'module' => 'brand',
        'url' => 'brand/brand',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '品牌列表',
            'icon' => '',
            'module' => 'brand',
            'url' => 'brand/brand/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
          [
            'title' => '品牌系列',
            'icon' => '',
            'module' => 'brand',
            'url' => 'brand/series/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加',
                'icon' => '',
                'module' => 'brand',
                'url' => 'brand/series/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'module' => 'brand',
                'url' => 'brand/series/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'module' => 'brand',
                'url' => 'brand/series/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '禁用',
                'icon' => '',
                'module' => 'brand',
                'url' => 'brand/series/disable',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '启用',
                'icon' => '',
                'module' => 'brand',
                'url' => 'brand/series/enable',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '编码管理',
        'icon' => '',
        'module' => 'brand',
        'url' => 'brand/type',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '编码列表',
            'icon' => '',
            'module' => 'brand',
            'url' => 'brand/type/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加',
                'icon' => '',
                'module' => 'brand',
                'url' => 'brand/type/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'module' => 'brand',
                'url' => 'brand/type/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'module' => 'brand',
                'url' => 'brand/type/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '禁用',
                'icon' => '',
                'module' => 'brand',
                'url' => 'brand/type/disable',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '启用',
                'icon' => '',
                'module' => 'brand',
                'url' => 'brand/type/enable',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
        ],
      ],
    ],
  ],
];
