<?php
return [
  [
    'title' => '库存',
    'icon' => 'aicon ai-shezhi',
    'module' => 'stock',
    'url' => 'stock',
    'param' => '',
    'target' => '_self',
    'debug' => 0,
    'system' => 0,
    'nav' => 1,
    'sort' => 100,
    'childs' => [
      [
        'title' => '库存',
        'icon' => '',
        'module' => 'stock',
        'url' => 'stock/index',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '库存',
            'icon' => '',
            'module' => 'stock',
            'url' => 'stock/index/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加',
                'icon' => '',
                'module' => 'stock',
                'url' => 'stock/index/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '扫描添加',
                'icon' => '',
                'module' => 'stock',
                'url' => 'stock/index/import',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '修改',
                'icon' => '',
                'module' => 'stock',
                'url' => 'stock/index/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '库存明细',
            'icon' => '',
            'module' => 'stock',
            'url' => 'stock/index/detail',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
        ],
      ],
      [
        'title' => '出库',
        'icon' => '',
        'module' => 'stock',
        'url' => 'stock/out',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 0,
        'childs' => [
          [
            'title' => '出库记录',
            'icon' => '',
            'module' => 'stock',
            'url' => 'stock/out/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '扫描出库',
                'icon' => '',
                'module' => 'stock',
                'url' => 'stock/out/import',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
        ],
      ],
    ],
  ],
];
